---
# install_k3s/tasks/kubeconfig.yml

#
# kubeconfig
#

- name: 'Check if we already have a k3s-kubeconfig file'
  stat:
    path: 'k3s-kubeconfig'
  delegate_to: 'localhost'
  become: 'false'
  register: does_k3s_kubeconfig_exist

- name: 'Fetch kubeconfig to Ansible control node'
  fetch:
    src: '/etc/rancher/k3s/k3s.yaml'
    dest: 'k3s-kubeconfig'
    mode: '0600'
    flat: 'yes'
  when:
    - 'not does_k3s_kubeconfig_exist.stat.exists | bool'

- name: 'Change server IP in kubeconfig file to external_ip'
  lineinfile:
    path: 'k3s-kubeconfig'
    regexp: '(\s*)server: https://127.0.0.1:(.*)'
    line: '\1server: https://{{ external_ip }}:\2'
    backrefs: 'true'
  delegate_to: 'localhost'
  become: 'false'
  ignore_errors: "{{ ansible_check_mode }}"
