---
# install_k3s/tasks/main.yml

- name: 'Set systemd unit name on agents'
  set_fact:
    systemd_unit_name: 'k3s-agent.service'
  when: 'k3s_node_type == "agent"'

- name: 'Set uninstall script name on agents'
  set_fact:
    uninstall_script_name: 'k3s-agent-uninstall.sh'
  when: 'k3s_node_type == "agent"'

- name: 'Run binary.yml'
  include_tasks: 'binary.yml'

- name: 'Run configuration.yml'
  include_tasks: 'configuration.yml'

- name: 'Run scripts.yml'
  include_tasks: 'scripts.yml'

- name: 'Run service.yml'
  include_tasks: 'service.yml'

- name: 'Run kubeconfig.yml'
  include_tasks: 'kubeconfig.yml'
  when: 'k3s_node_type == "server"'

- name: 'Run token.yml'
  include_tasks: 'token.yml'
  when:
    - 'k3s_node_type == "server"'
    - 'fetch_token | bool'
