---
# install_k3s/tasks/main.yml

- name: 'Run binary.yml'
  include_tasks: 'binary.yml'

- name: 'Run configuration.yml'
  include_tasks: 'configuration.yml'

- name: 'Run service.yml'
  include_tasks: 'service.yml'

#
# Scripts
#

- name: 'Create the uninstall script'
  template:
    src: 'k3s-uninstall.sh.j2'
    dest: '{{ path_to_install_to }}/k3s-uninstall.sh'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Create the killall script'
  template:
    src: 'k3s-killall.sh.j2'
    dest: '{{ path_to_install_to }}/k3s-killall.sh'
    owner: 'root'
    group: 'root'
    mode: '0755'

#
# kubeconfig
#
- name: 'Fetch kubeconfig to Ansible control node'
  fetch:
    src: '/etc/rancher/k3s/k3s.yaml'
    dest: 'k3s-kubeconfig'
    mode: '0600'
    flat: 'yes'

- name: 'Change server IP in kubeconfig file to external_ip'
  lineinfile:
    path: 'k3s-kubeconfig'
    regexp: '(\s*)server: https://127.0.0.1:(.*)'
    line: '\1server: https://{{ external_ip }}:\2'
    backrefs: 'true'
  delegate_to: 'localhost'
  become: 'false'
  ignore_errors: "{{ ansible_check_mode }}"
