---
# install_k3s/tasks/main.yml

- name: 'Run binary.yml'
  include_tasks: 'binary.yml'

- name: 'Run configuration.yml'
  include_tasks: 'configuration.yml'

- name: 'Run scripts.yml'
  include_tasks: 'scripts.yml'

- name: 'Run service.yml'
  include_tasks: 'service.yml'

- name: 'Run kubeconfig.yml'
  include_tasks: 'kubeconfig.yml'

- name: 'Run token.yml'
  include_tasks: 'token.yml'
