---
# install_k3s/tasks/set_facts.yml

#
# different settings on agents
#

- name: 'Set systemd unit name on agents'
  set_fact:
    systemd_unit_name: 'k3s-agent.service'
  when: 'k3s_node_type == "agent"'

- name: 'Set uninstall script name on agents'
  set_fact:
    uninstall_script_name: 'k3s-agent-uninstall.sh'
  when: 'k3s_node_type == "agent"'

